### ISSUE TITLE
`passthru` attribute is not passed through

### ISSUE THREAD

**Issue by avdv** [zaninime/sbt-derivation#13]
I am trying to migrate to version 2.

In my project I am using
```nix
passthru = { exePath = "/bin/scalals"; }
```
and it was working fine. After upgrading to `sbt.lib.mkSbtDerivation` it is no longer working.

Looking into https://github.com/zaninime/sbt-derivation/blob/master/lib/sbt-derivation.nix I can see that the `passthru` argument is never actually used, and the `passthru` attribute of the `args` is always overriden to just `{ dependencies = dependencies; }` here:
https://github.com/zaninime/sbt-derivation/blob/fe0044d2cd351f4d6257956cde3a2ef633d33616/lib/sbt-derivation.nix#L64

**Comment by zaninime** [comment]
Thanks for the report! Should be good to go now.
