### ISSUE TITLE
Taking long time for resolving dependencies and build

### ISSUE THREAD

**Issue by yogeshsajanikar** [zaninime/sbt-derivation#19]
I am using sbt-derivation to build against multiple scala versions. I noticed that the build takes much longer than running plain sbt. Is there a way to optimize the build?

**Comment by zaninime** [comment]
Hi @yogeshsajanikar, thanks for opening the issue. Do you have any number at hands? Did you run the build outside nix from a clean state?

**Comment by zaninime** [comment]
Stale, closing. Feel free to reopen by providing additional details.

**Comment by yogeshsajanikar** [comment]
Apologies for not getting back earlier. I do run build outside from a clean slate. I will re-open this issue when I get more data.
