### ISSUE TITLE
sbt.internal.inc.InvalidComponent: The compiler bridge sources ... could not be retrieved

### ISSUE THREAD

**Issue by gvolpe** [zaninime/sbt-derivation#2]
Hi, thanks a lot for working on `sbt-derivation`!

I've been trying to get it working together with `sbt-native-packager` without much success and I was wondering if you could give it a quick look? https://github.com/gvolpe/sbt-nix.g8/pull/3

Long story short, `nix-build` works but the resulting binary gives me the following error:

```shell
> result/bin/sbt-nix-wrapper
Error: Could not find or load main class demo.Hello
Caused by: java.lang.ClassNotFoundException: demo.Hello
```

If I run the same command `sbt "sbt-nix-wrapper/stage"` manually, the resulting binary runs fine so I'm a bit lost.

I looked at https://github.com/zaninime/xplane-rest as a guide and, *unrelated*, I noticed I couldn't update neither Scala nor Sbt versions in this application without getting errors, not sure if that's intended?

AFAICS the biggest difference is that my project is multi-module whereas yours is single-module.

Any help much appreciated :)

**Comment by zaninime** [comment]
Hi Gabriel!

I pulled your repo and tried doing a couple of local builds to see what was going on. I usually take the "reverse engineering" path, so here's how I found the clue:

```
$ nix-build wrapper.nix
[...]
[warn] You have no main class in your project. No start script will be generated.
[warn] You have no main class in your project. No start script will be generated.
[success] Total time: 0 s, completed Oct 5, 2020, 8:43:33 AM
[...]
```
A quick check in `result/lib/sbt-nix-wrapper`:
```
$ ls -lha result/lib/sbt-nix-wrapper
total 16M
dr-xr-xr-x 1 root root  332 Jan  1  1970 .
dr-xr-xr-x 1 root root   30 Jan  1  1970 ..
-r--r--r-- 1 root root  297 Jan  1  1970 dev.profunktor.sbt-nix-wrapper-0.1.0-SNAPSHOT.jar
-r--r--r-- 1 root root 5.7M Jan  1  1970 org.scala-lang.scala-library-2.13.3.jar
-r--r--r-- 1 root root 5.0M Jan  1  1970 org.typelevel.cats-core_2.13-2.2.0.jar
-r--r--r-- 1 root root 5.0M Jan  1  1970 org.typelevel.cats-kernel_2.13-2.2.0.jar
```

The fact that the your jar was only 297 bytes was already fishy enough. So I looked again in the build log if there was anything else that was out of order but couldn't find anything. Therefore, I looked into the `src` you declare. Again, from the log:
```
building '/nix/store/lgyc4j6v2frrc1nycr90csypmpivsvw9-sbt-nix-wrapper-1.0.0.drv'...
unpacking sources
unpacking source archive /nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source
source root is source
```

A quick `find /nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source` reveals the problem:
```
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source/build.sbt
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source/project
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source/project/Dependencies.scala
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source/project/build.properties
/nix/store/5f1g56vc4f0f82jflk3b2vfa0zisjfkj-source/project/plugins.sbt
```

The `sourceByRegex` that you specify doesn't work the way you wanted. I also struggled a lot with it and eventually settled on [hercules-ci/gitignore.nix](https://github.com/hercules-ci/gitignore.nix) for conciseness and maintainability. If you wish to further filter out files, it composes well with the `cleanSourcesWith` functions, without creating intermediate derivations.

Hope that helps!

**Comment by gvolpe** [comment]
Thanks a lot for having a look @zaninime ! You gave me enough hints to spend my evening, I'll make sure to comment here whenever I find a way to fix it in case someone comes across the same issue :)

**Comment by gvolpe** [comment]
I managed to get the `sourceByRegex` working as I wanted:

```shell
> find /nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source 
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/build.sbt
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/project
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/project/Dependencies.scala
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/project/build.properties
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/project/plugins.sbt
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper/src
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper/src/main
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper/src/main/scala
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper/src/main/scala/demo
/nix/store/kjqv1xhsa5kj2r7r8i0lg5pcgbhqgllm-source/modules/wrapper/src/main/scala/demo/Hello.scala
```

Though, I now get a different error that I also experienced when trying to update dependencies in the project `xplane-rest`. Any ideas what it might cause it?

```scala
[info] welcome to sbt 1.3.13 (N/A Java 11.0.8)
[info] loading settings for project source-build from plugins.sbt ...
[info] loading project definition from /build/source/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 1 Scala source to /build/source/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] loading settings for project root from build.sbt ...
[info] set current project to root (in build file:/build/source/)
[info] Wrote /build/source/modules/wrapper/target/scala-2.13/sbt-nix-wrapper_2.13-0.1.0-SNAPSHOT.pom
[info] Main Scala API documentation to /build/source/modules/wrapper/target/scala-2.13/api...
[info] Compiling 1 Scala source to /build/source/modules/wrapper/target/scala-2.13/classes ...
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.13:1.3.5.
[info] Attempting to fetch org.scala-sbt:compiler-bridge_2.13:1.3.5.
[error] ## Exception when compiling 1 sources to /build/source/modules/wrapper/target/scala-2.13/classes
[error] sbt.internal.inc.InvalidComponent: The compiler bridge sources CoursierModuleDescriptor(ModuleDescriptorConfiguration(false, None, org.scala-sbt.temp:temp-module-52f238aede5a1d8d7a484c2bec27a144810e2ac0:1.3.5:compile, ... TRUNCATED ... ) could not be retrieved.
[error]
[error]         Note: Unresolved dependencies path:
```

I updated the PR, you can see the error on the CI build as well: https://github.com/gvolpe/sbt-nix.g8/pull/3/checks?check_run_id=1210342500

**Comment by zaninime** [comment]
It took a little bit longer than expected, sorry for that.

I just "released" a new version of `sbt-derivation` that allows the user to pick which command to use to properly download all the dependencies. In a newer version of either sbt or Scala, sbt became more lazy and wanted to download the compiler interface only during build time.

For your project specifically, you now need to add:

```nix
sbt.mkDerivation {
 # ...

  depsWarmupCommand = ''
    sbt "sbt-nix-wrapper/compile"
  '';

# ...
}
```

and of course reset the `depsSha256`. I managed to run `result/bin/sbt-nix-wrapper`:
```
$ ./result/bin/sbt-nix-wrapper
Hello sbt-nix-wrapper!
```

**Comment by gvolpe** [comment]
Thanks a lot @zaninime !

I'll give it a try as soon as I can. FYI I'll be speaking at [Nixcon](https://2020.nixcon.org/) next week and I was hoping I could show an example using `sbt-derivation`, to create more awareness of your project. It seems it will actually happen! :)

**Comment by gvolpe** [comment]
It worked! :tada:

**Comment by zaninime** [comment]
Perfect, glad to hear that! :tada:
