### ISSUE TITLE
compiler-interface is non-deterministic

### ISSUE THREAD

**Issue by chriswarbo** [zaninime/sbt-derivation#7]
I'm adding sbt-derivation to some old Scala projects, and am getting non-deterministic `deps` outputs. I've tracked this down to the tar.zstd file containing `.nix/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.15/org.scala-sbt-compiler-interface-0.13.15-bin_2.12.10__60.0/org.scala-sbt-compiler-interface-0.13.15-bin_2.12.10__60.0.jar` which contains timestamps.

I notice the following output during the build:

```
[info] 'compiler-interface' not yet compiled for Scala 2.12.10. Compiling...
[info]   Compilation completed in 5.353 s
```

This might be due to a weird mix of older SBT versions (0.13.15) and newer Scala versions (2.12.10). I can make the result deterministic by adding an extra call to `strip-nondeterminism`, e.g.:

```nix
with {
  raw = sbt.mkDerivation { ... };
};
raw.overrideAttrs (rawOld: {
  deps = rawOld.deps.overrideAttrs (depsOld: {
    postBuild = ''
      ${depsOld.postBuild or ""}
      echo "fixing-up the compiler interface" 1>&2
      find .nix -name 'org.scala-sbt-compiler-interface*' -type f -print0 |
        xargs -r0 strip-nondeterminism
    '';
  });
})
```

I think adding a step like this to the `buildPhase` would avoid this problem.

**Comment by zaninime** [comment]
It's now in master: https://github.com/zaninime/sbt-derivation/blob/master/lib/dependencies.nix#L74
