### ISSUE TITLE
Avoid Building the Entire Project Just to Fetch Dependencies

### ISSUE THREAD

**Issue by nrdxp** [zaninime/sbt-derivation#8]
Using sbt-derivation on a work project, my biggest frustration was the fact that I had to essentially always build the project twice, or even three times, to update the hash, to generate the dependency derivation with the proper hash and then finally to build the actual Scala project.

I have been looking for a while for a command that would download all project dependencies without building any artifacts and I seem to have arrived on one that actually works (at least on my work project). If I just add the built in dependency tree plugin to "project/plugins.sbt" with `addDependencyTreePlugin`, and then run the command `sbt dependencyList` it pulled all required project dependencies.

There was one remaining issue with the compiler bridge, so the actual Scala package build was still failing with just this command. After trying to find a solution, I discovered after basically testing every possible sbt command in a repl, that the `consoleQuick` command was the one command I found that initiated a build of the compiler bridge without building the entire rest of the project.

So the final `depsWarmupCommand` is just `sbt "dependencyList ; consoleQuick" <<< ":quit"`, and with that I was able to generate a working dependency derivation without building any project code. I hope this could be accomplished with `sbt-derivation` itself (maybe by installing the dependency tree plugin globally for it's call to `sbt`?) to make for a lighter weight solution than `sbt compile` by default.

**Comment by zaninime** [comment]
Hi @nrdxp and thanks for taking the time for looking into this and finding a solution that we could potentially apply directly at the `sbt-derivation` level.

From your message, I understood that you (more or less) followed these steps:
1. Add the dependency tree plugin (at the project level)
2. Changed the `depsWarmupCommand` to `sbt "dependencyList ; consoleQuick" <<< ":quit"`
3. Built the derivation normally

Is that correct? Did your "app" build correctly and run correctly?

Second question: what happens when you `consoleQuick` without `dependencyList` before?

**Comment by nrdxp** [comment]
> From your message, I understood that you (more or less) followed these steps...

Yes that is accurate, and the app builds and runs correctly. 

> Second question: what happens when you consoleQuick without dependencyList before?

With just `consuleQuick`, not all dependencies were fetched so the build failed.

**Comment by zaninime** [comment]
@nrdxp, would you mind trying setting this in your project:
```nix
{
  # in the derivation
  depsWarmupCommand = ''
    sbt "dependencyPicklePath; compilers"
  '';
}
```

This makes the trick for me. I will try it on more projects, and I might change it as the new default command for fetching dependencies.

**Comment by nrdxp** [comment]
So that command still compiles large parts of the local project which I was specifically trying to avoid.

**Comment by zaninime** [comment]
I guess you have multiple modules/projects declared in your `build.sbt` then. Can you try then `externalDependencyClasspath; compilers`?

**Comment by nrdxp** [comment]
That command didn't seem to pull enough dependencies to build Nix with. I am going a bit farther though, and generating a custom lockfile to avoid relying on the FOD all together: https://github.com/zaninime/sbt-derivation/issues/5#issuecomment-1124181516  

Maybe it would work with an unmodified sbt-derivation.  After reviewing the build error, it looks like it didn't pull the compiler bridge sources. so just modifying it to `sbt "externalDependencyClasspath; consoleQuick" <<< ":quit"` was enough to rebuild the exact lockfile as my previous command without the need for the dependency tree plugin, so that is definitely an improvement regardless.

**Comment by tpwrules** [comment]
In one of my projects, I ended up putting the following:
```
  # sbt needs to compile at least one file in order to download all the
  # dependencies, but we don't want it to compile all of cohmetrix in order to 
  # save time and resource hassles. so delete the source and compile a fake file
  # to get sbt to do its job properly.
  depsWarmupCommand = ''
    rm -rf src
    mkdir -p src/main/scala
    touch src/main/scala/hi.scala
    sbt compile
  '';
```

I don't know enough to verify that the reasoning is correct but it seems reasonable neough.
