### ISSUE TITLE
zstd compression is not stable

### ISSUE THREAD

**Issue by tpwrules** [zaninime/sbt-derivation#9]
While zstd somewhat uniquely guarantees reproducibility for multithreaded compression, it doesn't guarantee reproducibility if the version changes. This is causing trouble for me when nixpkgs upgrades zstd as my dependency archive hashes sometimes change despite the tar inside being identical.

I have two ideas:
1. Use boring old and stable gzip, with `-n` so it doesn't write a timestamp and break reproducibility.
2. Forego compression entirely. The dependencies are 99% already compressed JARs, and at least on my projects compression saves maybe 10% of the file size. Perhaps it should just be left as a .tar

**Comment by zaninime** [comment]
Hi @tpwrules and thanks for opening this issue. This is indeed a concern. The main reason for which I used zstd in the first place is because the ecosystem was mostly moving torwards it.

I tried your option 1 in the past and found it too slow. I wouldn't consider it.

In find option 2 going more in the right direction, with the catch that I would make it controllable by a flag (the default of which is to be discussed). For big projects 10% is quite a lot of space, and I think it would be also fine to warn users that updating zstd / nixpkgs might trigger a change in the hash when enabling compression.

What are your thoughts?

**Comment by tpwrules** [comment]
I want to make clear that I'm not a Java/Scala programmer and have only a surface-level understanding of the ecosystem. You probably have a lot more exposure to a wider variety of projects than me. I'm most interested in stability so I can publish a project which uses an sbt-based derivation and have one hash for whatever versions of nixpkgs my users wish to try with. They are also not likely to need to change the dependencies. So for me, "10%" is maybe 50 megabytes at the absolute worst. I don't know what a big project is to you. I also don't know how often typical developers update their dependencies.

I did have a third idea which is to just not tar up anything and put the dependency `.nix` folder in the store directly. I would imagine that as soon as you have two similar projects, or two versions of the same project, store optimization and hard linking will give you a way bigger win than compression ever could. This also means that the dependency unpacking step could theoretically be simplified to `ln -s`, meaning you don't need enough disk space or RAM to hold all your dependencies a second time during the build.

I'm also not sure what changing sbt or JVM versions will do to reproducibility. I verified for my projects that changing sbt between 1.6.1 and 1.6.2 does not change the dependency hash. But maybe this means expecting the dependency hash to be constant across nixpkgs versions is a fool's errand. For now I've pinned the inputs to sbt-derivation itself (including zstd) and let them be independent of the rest of the project.

My thought is to make uncompressed (or even unpacked, assuming sbt is happy with symlinked read-only cache dirs) dependency storage the default and clarify the implications of changing nixpkgs versions on the hash. Zstd is a lot faster moving than sbt it seems, and it's the one that's actually given me problems.

**Comment by zaninime** [comment]
sbt (or coursier, the downloader under the hood) was not so happy in the past with read-only paths. At the very least it tries to write some logs and other artifacts (that are stripped during the build). So what we would need to do instead is create writeable folders that resemble the ones in the deps, then create symlinks to the files stored in the nix store.

Also, while sbt is not fast-moving, it is still moving. From time to time there's a difference in which files are downloaded / stored. The underlying java doesn't (I'd say shouldn't) change the result in any case.

I'll try to add a flag to disable compression altogether. The symlinking approach would require a bit more effort and at the moment I can't commit to make it happen. This project is open for PRs, though.

**Comment by tpwrules** [comment]
I've observed sbt downloads the version the project is defined to use as the first thing it does, so hopefully that does not change often at all.

Adding the flag would be great. I don't really have a wide base of projects to test the viability of the symlink approach on.

**Comment by zaninime** [comment]
Addressed in 0b4b3e4dcfd9322936531df3a0332697dd69f77d. Note that the project now exposes a slightly different API, including the option of choosing the archival strategy.

Can you please confirm that it works for you?

**Comment by tpwrules** [comment]
Yes, I can confirm that it works for me. However, the new sbt cache location causes problems. I'm preparing a PR to address them.
